### ISSUE TITLE
Add .first and .last to Array

### ISSUE THREAD

**Issue by dphaener** [Legitcode/rubyfill#3]

**Comment by zackify** [comment]
@rampage1213

**Comment by zackify** [comment]
Hey so, quintin did `array.first` but I don't think it's possible to customize a get method on define property while ALSO adding a function for Array.first. ex you can't have .first be custom and have .first(blah) work at the same time.

**Comment by dphaener** [comment]
You're correct. You cannot. The only reason it works in Ruby is because you can invoke a method without the ().

**Comment by zackify** [comment]
closed via #9
